pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.0.100'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack the project - $(buildConfiguration)'
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
 
- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    #feedsToUse: 'select'
    publishVstsFeed: 'https://stenrosendahl0473.pkgs.visualstudio.com/4dc9b01f-f058-46ac-bda3-0e7fb685d254/_packaging/b09fd9ab-66b0-448d-be17-146dfbec2822/nuget/v2/'
    #publishVstsFeed: 'Tailspin.SpaceGame.Web.Models'
    allowPackageConflicts: true
    #packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    #nuGetFeedType: 'internal'
    #publishVstsFeed: '4dc9b01f-f058-46ac-bda3-0e7fb685d254/b09fd9ab-66b0-448d-be17-146dfbec2822'
  condition: succeeded()
    